DEFINE
// Refence Function is Format Number
    FUNCTION fxFormatNumber = ( xNumber: expr, xSell : int64 ) =>
        VAR _Formato = 
        SWITCH(
            TRUE(),
            ABS( xNumber ) >= 1000000, "R$ #,#0,,M",
            ABS( xNumber ) >= 1000, "R$ #,#0,K",
            "R$ #,#0.00" )
        VAR _Formato2 = 
        SWITCH(
            TRUE(),
            ABS( xNumber ) >= 1000000, "#,#0,,.00M;-#,#0,,M",
            ABS( xNumber ) >= 1000, "#,#0,.00K;-#,#0,K",
            "#,#0.00;-#,#0.00" )
        VAR _Formato3 =   "R$ #.##"
        VAR _Formato4 = "R$ #,##0"

        VAR _Formato5 = "R$ #,#0;R$ -#,#0"

        VAR _ForPercent = "0.0%"
        RETURN
        SWITCH( 
            TRUE(), 
            xSell = 1, _Formato, 
            xSell = 2, _Formato2,
            xSell = 3, _Formato3,
            xSell = 4, _Formato4,
            xSell = 5, _ForPercent,
            xSell = 6 , _Formato5
            )
// Format
    FUNCTION fxFORMAT = ( xNumber: EXPR , xsell : INT64) =>
        FORMAT( xNumber , fxFormatNumber( xNumber, xsell ), "pt-BR" )


// fx calcula por UF
    FUNCTION fxUFValorAberto = ( xNumber: EXPR, xUF: STRING ) =>
        CALCULATE( xNumber, TB_CLI[sigufs] = xUF )


// fx Color UF conforme o Acumulado
    FUNCTION fxColorHTMLMapa = ( xUF: STRING ) =>
            VAR _TABELA =
            ADDCOLUMNS(
                VALUES(TB_CLI[sigufs]),
                "@Total", [01. % Acumulado UF]
            )
            VAR _RESULT = 
            MAXX(
                FILTER(
                    _TABELA,
                    [sigufs] = xUF
                ),
                [@Total]
            )
            VAR _RETURNCOLOR = 
            SWITCH(
                TRUE(),
                _RESULT <= 0.3, 0,
                _RESULT > 0.3 && _RESULT <= 0.5, 24,
                _RESULT > 0.5 && _RESULT <= 0.8, 48,
                _RESULT > 0.8 && _RESULT <= 0.9, 72,
                _RESULT > 0.9 && _RESULT <= 0.95, 96,
                _RESULT > 0.95, 120 )

            RETURN _RETURNCOLOR

    // fx Tabela Configuração de Aberturas
        FUNCTION fxFluxoCaixa = ( xCOD: INT64 ) =>
        SELECTCOLUMNS(
                FILTER(
                    DATATABLE(
                        "xCOD", INTEGER,
                        "CtaFin", INTEGER,
                        {   -- Deducoes Receita CTA
                            { 1, 750 }, { 1, 2370 }, { 1, 790 }, { 1, 800 }, { 1, 740 }, { 1, 760 },

                            -- Custos de Producao
                            {2, 1060 },{2, 2040 },{2, 3730 },{2, 850 },{2, 1800 },{2, 1080 },{2, 1100 },{2, 1890 },{2, 530 },{2, 540 },{2, 610 },{2, 640 },{2, 630 },{2, 660 },{2, 670 },{2, 620 },{2, 520 },{2, 580 },{2, 3850 },{2, 710 },{2, 650 },{2, 560 },{2, 700 },{2, 570 },{2, 3910 },{2, 680 },{2, 590 },{2, 500 },{2, 3050 },{2, 3350 },{2, 3921 },{2, 2840 },{2, 2540 }, 

                            -- DESPESAS COMERCIAIS E DISTRIBUIÇÃO
                            {3, 1330 },{3, 3640 },{3, 1550 },{3, 4061 },{3, 3610 },{3, 3040 },{3, 2490 },{3, 4051 },{3, 3860 },{3, 1250 },{3, 1650 },{3, 1160 },{3, 1640 },{3, 490 },{3, 1720 },{3, 1750 },{3, 3140 },{3, 1390 },{3, 1340 },{3, 2520 },{3, 4001 },{3, 1290 },{3, 1320 }, 

                            -- DESPESAS ADMINISTRATIVAS
                            {4,150 },{4,3981 },{4,840 },{4,3150 },{4,1070 },{4,2810 },{4,920 },{4,2030 },{4,2020 },{4,1980 },{4,1960 },{4,190 },{4,280 },{4,2000 },{4,3780 },{4,1110 },{4,2530 },{4,2950 },{ 4,2820 },{ 4,2640 },{ 4,2970 },{ 4,3830 },{ 4,2480 },{ 4,310 },{ 4,1130 },{ 4,290 },{ 4,200 },{ 4,240 },{ 4,2260 },{ 4,3530 },{ 4,930 },{ 4,1200 },{ 4,2510 },{ 4,1730 },{ 4,1910 },{ 4,1930 },{ 4,870 },{ 4,860 },{ 4,1000 },{ 4,2330 },{ 4,2010 },{ 4,1700 },{ 4,1030 },{ 4,3560 },{ 4,940 },{ 4,1920 },{ 4,960 },{ 4,1140 },{ 4,170 },{ 4,3660 },{ 4,230 },{ 4,350 },{ 4,880 },{ 4,980 },{ 4,2360 },{ 4,160 },{ 4,990 },{ 4,140 },{ 4,970 },{ 4,1850 },{ 4,2651 },{ 4,1090 },{ 4,1190 },{ 4,210 },{ 4,270 },{ 4,180 },
                        
                            -- Imposto sobre lucro
                            { 5,2670 }, {5, 770 },

                            -- Receitas / Despesas Financeiras
                            { 6, 70 }, { 6, 420 },

                            -- Fluxo Caixa de Investimentos
                            {7,3880},{7,2100},{7,2760},{7,2150},{7,479},{7,450},{7,2080},{7,2140},{7,1020},{7,2680}
                        }
                    ),
                    [xCOD] = xCOD
                ),
                "CtaFin", [CtaFin]
            )
    // fx Tabela Dinamica para contas fixas
        FUNCTION fxADMFixaValor =
        ( xID: STRING ) =>
                SWITCH(
                    TRUE(),
                    xID = "adto_motorista", CALCULATE( [10. Adiantamento Motorista] ),
                    xID = "ir", CALCULATE( [10. IR] ),
                    xID = "Tarifas" , CALCULATE( [10. Tarifa] ),
                    xID = "adtFor",CALCULATE( [10. Adiantamento Fornecedores] ),
                    xID = "cambiopassivo", CALCULATE( [10. Cambio Passivo] ),
                    xID = "despesasFinimp", CALCULATE( [10. Despesas de Finimp] ),
                    xID = "dJuros", CALCULATE( [10. Juros] ),
                    xID = "dCheques", CALCULATE( [10. CHEQUE] ) ,
                    xID = "dVarCambial", CALCULATE( [10. Varicao Cambial] ),
                    xID = "caixa_fruts_entrada",  CALCULATE( [10. Entrada FRUTS] ),
                    xID = "caixa_fruts_saida",    CALCULATE( [10. SAidas FRUTS] ),
                    BLANK()
                )




                