table Base_Classificacao
	lineageTag: 0b8a939e-1389-4f29-b344-90bafb354974

	column Cod
		dataType: int64
		formatString: 0
		lineageTag: 7afe540a-b315-49af-babf-789c8c68c5d4
		summarizeBy: none
		sourceColumn: Cod

		annotation SummarizationSetBy = Automatic

	column 'Descrição da Conta'
		dataType: string
		lineageTag: f341a630-9ddf-4222-a5c9-129fbc015f6c
		summarizeBy: none
		sourceColumn: Descrição da Conta

		annotation SummarizationSetBy = Automatic

	column 'Tipo Conta'
		dataType: string
		lineageTag: fa87bc9d-c684-41e4-8cf7-97a1147aff5d
		summarizeBy: none
		sourceColumn: Tipo Conta

		annotation SummarizationSetBy = Automatic

	column 'Classificação Fluxo de Caixa'
		dataType: string
		lineageTag: 9ca63984-7fd0-4b2c-bef3-4fc93f384151
		summarizeBy: none
		sourceColumn: Classificação Fluxo de Caixa

		annotation SummarizationSetBy = Automatic

	column 'Grupo  Caixa '
		dataType: string
		lineageTag: cf29485c-8ba7-4ed8-8467-4b470a90f941
		summarizeBy: none
		sourceColumn: "Grupo  Caixa "

		annotation SummarizationSetBy = Automatic

	partition Base_Classificacao = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xV1Lc+O4Ef4rrDntVm3WoihZ0lGWrVlv7BnF8viS2gNEwjI2JKGQouKdW37KJIetSdWcpnLZK/9YGmiQAim+JJGTuaxXAL7Go9EvNMC//vWNNRmab354M3UY8bfEo/6WG8R4jnybcT/+FDAeQrEfuW6uVnjw/7/8IOAGBXCPNLApC3hofLf4+fuj8HpmL483cxn8l4oG76NtQELjxof/OOQQohByNBCQM+6xMIz/zY051Ih/J8YV8W0xYgKl1zTc0BCg58yHn6HzEr3k5xlhr2T/GzeQEPyTbTYBtRmJfxfEdJCp4zGfhdD3LdudgD/pYRObi8EZMw6lDnN4BdJRBPqToaKwIfYLTCOFLkfEFzVaHMeg19ObpMvQ1jAGo6HexL4wHknAnuHPZO4MhxrX0cZlNtm2R/YyMywgMeOrQLJaWww2tnolbQS5W2/Dgy3yXVscMZKDuvGApcMt8/h+uXQ5cdw89QXk7ft5W/MuJcbPUZDvXCvggz04TPH7DQ3UxhYspLHT7IX+PaKtkbUakm2fi0eTlDI1vMjdEiO8MBYEJLqLYrU1bu5plO4FJaEvyJqH37dHYk/jgcG0GUtiE6etIQzGZgoPkzQFiWmzjVopkDuCHVtjRWus8eIhNe7pirKV0Q339JYgyqgh5ED8uUgQtMN6eXpYg+21extkhvAPCh9oKFjO4cY7MX9yiwkbiLiZQr310eMZQdkjeYX6i4DDwrQ3iMFoDGVPoNfU+s+It2LEhY0ahqCU25L/plyT6d8jFrJUAF2R+A+xZ2ckCLhNleq+9XdSRyRrNSMb+poi66UKelwAPePPoGnEaJj/Ev+XngQ8KQC+565zGppVgPZE4y925PKTAKVMuqL+M2VbftrkWbg3AQTWATY+97hDpGQ+ujcS6AaGt1HbTJoS/jMPvPjTFnTLCaAj8wAUTEmbgv39VQgMY3NxzhRaaJXMaRBIeGDmW4+vmMs+omw/Fu9ScvktyM51QARKutCg92AOEil7ylT0eqpVoH4XC0bZK0+Y/BRYC3lc/13ATn0nVdHHIo4n6CX5Yo1AEJ7CS2a+U3JhdpSdsk96Uj7cx5+AjXwiOCjDULe+E4ELwshJ4KY0Qu/BqpHIC7KVmtP4DsX1nDqgDpg0RI6Glmr6Xg4boD8Achh/cdlJwqInV2XJn7f/IMFp8kvulUexVzYu8cmaeqewsZyvvbWZGKHKCz/0yw9/UX8aD9SOghBWMI0SoFoWBBbCzdjvviUNdiB0udTIUHeLjk7ys5HtklAfygIy9vRCTbUzJKW8FgVp/MkoJ5s4OCdQkfOeQMl2j+ANhsJHoy0PSHLcE/UdbATGhhPhuupUtJ9PITLsoSu4Ii4wESiehUtCoSBCtIw8qGjMolCpEEktkZplreY88KGHDhdKP6nkKTsN99HCuALR7ksWuodtCjsesJlH8oVVWJemwkL+loJ9Q12x3jD7ZMdL0KuqV9KbJPTiTxswJct6rxdX4o0U3lswuchzGZxWWoVmjYcK7k55jgVYSVFltxIc2EDCYCjD0osr8XoK74G7L2VgaVkV0ihFir9ulZVRhLUvrWTFZJxLWgqVFFVO/CThw0fibSRjiWm+uCN2gH8WY1fUrpzOsU6tpN9pWRWSObFQX/oRqLNUUE43oJTcFzUlSRla7fm6e0V+k1HkecoZnIS6WUQ9Z6TWdSBXvZYoGkRHDKPDGbDUTssh6jb0PKBChIOAmoOvSYy66nXDH9VSVLrxLCoTaVcsaPw7kV5BjSPS9hpPelnyZdZmAelGjeo7MNA7QALScE8JhGu2+7HRSl5qNDpkmYkUNw8UBiAdPuFLgGGj7KpbH0wsl6RjSeMQN2DFR9soQEM+iwuKw1EWfu0wLcmwT/EXh0ryc654COYpcteHcXGxJUnwN7pl/jpPQJT9bSuaUmmrHnYgaYi0MUiwjv8jwlUy3OMBeVFzugJ7h9rsIHSaI9+ocVUf0KXZH3twD9yYcItsuUs4Um3aOZ4a6CVV2P1hr7hR6WQeh29d4qkfDdmuGvf0RbImMlo7BSsUplkaddEKrGDmEIdqM3MGGwww8uRHEjMEV2ctjsmE1fgThwE5UqMumXQAuuDDodyCMxJsyceuWH2s4gTP1MadfcV92tGa9QeDPDXhr1z/6QF3SRqw7WKkl/0i2txbdSVFBsUEN13tCNMaFRB8AqERkYB1NkpLERXnx5rTvSW+09XWxyDIjHOXBl0NC0mkAfkcdBck+zpJoQjl2SBb+11txsmBhrmm6ygsOHNucxuah+fq/k7ZKB3xSw/P8lm4cclvuCl8h3S1DYdy39+8wkZnqPcX108drSG6snOR3+EQ447/CvBF54ZtLiCSFMamoRxQt/O9MZSi7S7+lweWeVdbXnLmXSSyYXjYmd2iAsrJj2hSRZ2pPUv5vWqhnEbm3jkciaF46ofElXaT8VaYrVKCPlBhRi1Bz6MT0Al79nL0Q2mu+TzA020jtcw7mgBLHRismNuRXdhH3+heBOyFBSpCNwF4qruuZHZf8tCCgO1ri83R0bDGyrO9WED1rqYOIxRpNFspoC2N/3A6Uz+WoulxzSwDDdSOm5IOSbqZ30KHDyd4CAVDwChHpyLl/xsKGOTFZ7UyP6xZgT7o9YQPe8+cIg+2lERx9SoOxOifnlEoQRdv6k56CpvkKG3jz/sgtIyvWypQPQWeJFv2kcjjKNA8r8JJEMlGdMWcshB2g1Z1PbhMDptmvPywhhcc1BRhWSlWQJRdVQiXltYi9tPjn7AMLimqnesUC8hT1/jzugxQL69FHWdR77bVqFheh9ofJ+deksdswotBtdLajl7qiIJJ/hLFXzxml53rFNarpZL0exnZIvqz4O6m5GwnV6MWOTlZfGJbkT9Sxqx6cR2mdZlkyK9gU4Occ6FDd9EqYM/MFjyamO/ZWHF1/RxNlHEiJBx5abp5P0/2xtswFzwTET3shqg5RneS0ZC6e3V6Pqy0ImETchcdjpaAFYzeMGyCXqSnChcBTTVwAe0XsLd5chxapksOKjaigfwlNIYIoG1cKtO2AkMc4KOMhhVOLOwq9ZJo4aaEh/WE/xLtnd/2SJuYvnRH/RdSC53UajKksaXZF0zEmMGG84lKsmpzCNakn1fLUF06D95KRgx0Pjm8FFLdsEEHLhNZPWfutkqVZsobAI+SY/j9NEqrdEbcRPQUUCmv3IQfVEYCprnLZKD4X76I9xTLuZKKDVath5lUxKVNuHpfrxHzyY38yHw8VrpmbsPNU9ikybSZ6ZWkNOb4E1sDE+lZmukJbP0OaA6U6V2ax4UnncrvdOJPa8zrK/u7AsTELJwleF9Bk9P8korlBPo9uVrTEAzDUCQaJ9uPoOrwRY67TEBOsnPxf0pRDb1NNW0LEwZ12iAWeC5Pt9s+9NGN1vogJJAff3JZSKUbH8SfHdxYXfckPxtO9nZYx+QxW1wjr13x6576KL8M4hrJjyLcrd1W67YPJuYm5PogBAH7FpthMjGz1OfstSyWc9rwLnPD+zkK4i8OZsF0PLjL/NRqsbI0Sbv7Se7jtVKtH8ph634KzMkkRzo9+Efr2cYrNt2O/zK/zR6pS5+5/21mYJQnHrBVtE2uV3ctXnu9LBF5oAwrQL1vMPMWhq9+4gH3CZ4YODtuE3FxhIt7VqFdc336/PnHu3MLGop7SnL49zTI33QEDwh+LMqnOmnYaJpNXZmdpGyoBypuNclbPnlrayEmnVTIO/BOakaJx7KpCtc2eLXVdzLBy6I7agufRnoq1Yng1gilRuCRjzS5l3EuJmbnTHckWb9DO/J07EuVXBTQdXrNSOu+iEDwdfwlLMq+PGpiVIYIeCYETwFDUGYRrzfvTyeZZDXJyLF0u9LbKa3zcT9N9NkKKcn2+ZzgnWePGRvLilqiaJDv501c4CHBmjQJ6p/OMsmDBXaWa1pkyz4GLzNLlJFJHawfJt5gRoOjsLtZNdPUSIUXey8ZTyGFo3y+1MC8nj2NDhlipK4IJmZh6nxfEfc3489MZoAdFp9DctwvIykDgCr+1zrZwaiE7Azq0V9J6wSTm6YHBG98GqwpCGXeNk0TJfUds2l6Tb9BJONkcnjer6eKPBAYDBXhxZZJmYO8QbUIqGy7fOxmq/cxMTIlmbWgOyBoYXx1Ie7wg0gEnxEcRpbNK2qP2ljdDgD7MM1WvCO+/QJ/+ak/fr4wQ1/sge6Yyn1fgMCMvzos9xJHeyNTHV4K21pc4pTGt02U43W2RaeihOqGqJD7L0QeFXZheqETrVN7GzH/pQUlY01G5pvchdg75m3oR5K/K9IGsb4kFqkTH56aBMH54H28mfoo0pdTkXfz7EbpkUgnvgg+RHEDXC2z3g/uk9Qw9P7ycblcVE7PIGMOpKmvdeK1OQV8AuMOfOSCy3EHl6gqRriHaHwLK+9SYuDCjdYRZY2piVcN4s8VfrQ6LjH34G4Dxbgn0DTEP8QUVLJL27E28U1MF96/nRfKd3kOs6EzoYUH8QJeKHabPIhuEHZQqXaXKLpDm0liyh2L6lRSKb0aPuxj1Eo/6n5i8pZ6NT1VSTAa7EanPj6FXvk1k165cS+y7qR2Kl6lY+EnKvyUXDBqt/PqhiIJww5mxkJPWFoFdvpSj5qelmZHcvAjeWVtL2ovuzVkrnLpnpiuSPJQyxMNVhh6fEtCfMgxrYh2mZkJRiTFbivgvcRdxjfk9nus8BrA6WRGGTJzVz4vcjauiVHuW+i0npDb3tzjGzbvOEaeZuL+qbAeZEAt1eU5vXQ6sV4RsVsf3Cl5Wlp2h+hkgpimt7y5uzNu310Y8o/3Hx7bwO6P9funxgP/jbhbBtvmA/xfegZSsQFrWpZQtRSf7bir5WfrnKxK8NaxNqBcScmMoct5zQsuLhcMQatWhif564rgCfQ1eK5hgw2ekUOaftMSekr2C77acsV9mRh2OIiWyKj3yALmw0a8mHo8lM//yEQZe78aRZb3MXT6GFDMXNZQ5zwyv0uk5dRJsTPmUvnL1NNe3dsQ/4UUXxFri6yZ3kAQxXJOT8nZP2qi8ckN/Rwz7cB3PFgD2ewrnTXexzG0B/BPSKloBe7sNg2PH27mgholUwj/NI0qzuReExFe9JiyknXilL5K4sG/DKp8jjFNxKtCFjXjT/KFsFJ4zLWK/7mOMvGf7HMJSbGC0AplSMDWwnwSE1/7EwFBkQPhxp+3QXKAVohfVLUhLcwenLqgOuNPxhX3Vvl3pLOkMvyig+s3L5rSNnXac3zd/NBl7rADPb0DS+IzGcn7RtStcXIM6GrXkW+9+Ouu1sltsx+mqSzZIKCszpdvdQJGo6xPlCrb6j4UKZbwiPH2VQx+S2Es205p9dUjXrmkVO6LdngX4htwmorIa6dSSUwPkyupjO1tKiRM5qLpKyyXVN/inbVoEySvSMICvqWBNJAaT8/BNVaZQIlP/8NmcISNjTZR1WR11D2MPGBKZ0YlFllI5+5CfEQSX7akhhJKoMffox7Hl3wxaeMopX62dBjjrUCZpkSlUu52e5qTDMF7IQ9rYkvn7lL8nkUZSneE1ann4vHDG7yUpx6fTv7MNWmOO8pvqya7omqcHe1/KYnn8qpTVQpHWkHhqiIj8Z6gxLT4j6DC3QMFXpFNkMCoN7qKwK3RWJiPU5sHwgl8DMiKuC9JXLAlIsjxVyCIn+Mvdk4HnwfdH2sunyHPR730JZJ57oMybdEcqoSSTfxVXIk45cyyydJkv1Ain9KKfMWARRK6CSa+ib24bXE25OLevIJhG4Iw++wwu0X+xEtb87ePyxZ53lThOye5d1EbUzmeRSSFd8sWu435PrcP4rIVEx8FEE+QtjnT6nwgTPPB0GK/i+zmCWhNCCXvCrhkJdq0iKzi+DYI5UM/60ymGSI29VbcDWH2iXji0WZlp+tNIC+zkAuX+PgKFYn/KH0NrhGnyM9rLUEogmnJ2pxhEw+dKStwZM+Eljr9g8+eeeC1yRVo4D0RN/f2dVvw+DqcUkE6blUYrJlqFqv4E5dPmIvXBComJbEMSo2I3uEDMyl/iJMt+db8wZe0aixCfIRESx8tG4pK+5S2ORAjduRKhBaXAXPPD7ZQCfxhxUJQ/Sz4v1XdzdQpZpNebplOXEmVJLy8u8va1OKtex4aBVa2Ejby+s/8dnoxv7ndy5aaZnhSAHYHKBz5ApJ7FNU+XnlSvxniu0qG2Cc75vBju68BCSZCTzJ3geuInuFzFkJFG8uLORFWfPrVisYo5kh5OE/TN4UHxbW9UEr9YX5k73E6pH1xRHfxMqK61iuPmCNSF4urxexrmMk3K86EHGqQt+/ubx4f3p+JONAQ76eL6VlwlvosiIKLfPl1ljNH3cdkXQUqjLziw7LjgfECSe7raUXuuF7FyMNgNPP2YfFzSevwwhWm4kE7lb3zzPywtOVOPSyVbYlMPrtfGu/Ey/3ucc3xNQzZXKbLHkN5gNv69shmeDbHjhxn+gHDzPnxXgOeUZb/Agryw0h18wcDl0Uo8gOFUjvYkfy0mNJRc7C5G7ApkR9t2ai7Cvlf0NCWk3hY+Wzk/nCS9fsI31uEInubFExYY3B1+3XF/YOUiSYfpilaKKvXzwQaQvxK3D5q7PBmYCXw+Fh3us4PFA8yz0NNHoVReSR5hjz298KOD/vZhRSzgmHsMzqOx0SqJPlkzRl4/UFiPYYgVlW+x5LZfEUPlXYDuLH2qUrRvZVaqPTrOtlv6R3xc+I1Fk2AXu+7QJJNPrDsEcaD71vtQa+3rwBdAP9EJU7LLwXJHbtv1SLlcU8vDi+M7PfDHql4UC41y9uiOslSlVmtyUjRnm2LkoUzW/CpRvEiRmsz+cv/AA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Cod = _t, #"Descrição da Conta" = _t, #"Tipo Conta" = _t, #"Classificação Fluxo de Caixa" = _t, #"Grupo  Caixa " = _t]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Origem, {{"Cod", Int64.Type}, {"Descrição da Conta", type text}, {"Tipo Conta", type text}, {"Classificação Fluxo de Caixa", type text}, {"Grupo  Caixa ", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo de coluna alterado", each ([Cod] <> null)),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas Filtradas", {"Cod"})
				in
				  #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

