table TB_Apoio
	lineageTag: 53a96aa3-334b-435a-9fd8-446c402e9f68

	column potador
		dataType: string
		lineageTag: 864ca48f-d0d9-4e91-afb2-bed4747f1810
		summarizeBy: none
		sourceColumn: potador

		annotation SummarizationSetBy = Automatic

	column 'apoio para a view'
		dataType: string
		lineageTag: 69defa47-d5ea-4c61-a392-ac12bc457833
		summarizeBy: none
		sourceColumn: apoio para a view

		annotation SummarizationSetBy = Automatic

	column descrição
		dataType: string
		lineageTag: b9c94965-0202-44a2-91fd-b4532e2e58ac
		summarizeBy: none
		sourceColumn: descrição

		annotation SummarizationSetBy = Automatic

	column Carteira
		dataType: string
		lineageTag: 0740718b-2c40-4c7d-b6d9-870db27ddbcf
		summarizeBy: none
		sourceColumn: Carteira

		annotation SummarizationSetBy = Automatic

	column xCODCART
		dataType: double
		lineageTag: 0966cbef-4b84-4eec-abdd-b61d54b1b9fb
		summarizeBy: sum
		sourceColumn: xCODCART
		sortByColumn: Carteira

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition TB_Apoio = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tZXNjpswFIVfBWU9/ctEM8rSGMOQJgQZglRFs3DAjVwRTPnJO/Qxqi6qPgcv1msykxlahRSsZpXE535cn3uwt9uJufInNxPKY74TRy5K442RF/ILr1jCYMGq81TErGKlgVPBs4orhcXLWGat5PFmO3lAnj6EWrY2A4X6DAdFRL8RL9SHrH1C9W0llv5uzHA4IxCHPOVlC7DQJ/0u3BDpQ0xqBdoQf4lNPUMc0xthqZPKHUs9XrUMjKjmWLAXPgwnYLkrWBY/B90ZEfTXTczho0egZMTp8xoQ2Eg/4FiPAOne6BFMOub96PiA7Gg4IRJZXKcvLxgacQZ3GeDFnS4DJqK9l8C1RxzAXcZyHY44cLoMn5KVLmO1WY7IeJdBojEXUpdBCV6cGHXOC9b8bH5IY1EnIhYsBTUsvD3//nehQoeLDf1PaGSpMKHkKPesgr/lxd0qTfykaXNIorUS86NM65hdLnxRnGzy2g4zvpfQRV9hR9T6QJEqDuGULnNZwHBkcXk8f8gUAMas7reIF7uesbarbTwDlSy7zhJpBPLJXJ/t2QG0shuS9rUKZyBw8Sow2soeqY39QWhw+2z2aawJPzd9rRT/XWrLIoO0gzP9xZiqWxAXPBHVoELLVael7aJ3NnH7pUu7+aa0za9CsCubub2bTm9BsvINB+bLU+Pj/krJ7P39/B4km0x8lsXhml3T2fyDekDz/WstMogGNwh8y5/1bpbUZQWdij7Q428=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [potador = _t, #"apoio para a view" = _t, descrição = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Origem,{{"potador", type text}, {"apoio para a view", type text}, {"descrição", type text}}),
				    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Tipo Alterado", "Carteira", each Text.AfterDelimiter([descrição], "- "), type text),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Texto Inserido Após o Delimitador", "xCODCART", each if [Carteira] = "Descontada" then 100001 else if [Carteira] = "Simples" then 100002 else if [Carteira] = "Vinculada" then 100003 else if [Carteira] = "Rec. Judicial" then 100004 else if [Carteira] = "Advocaticio" then 100005 else if [Carteira] = "Devolucao" then 100006 else if [Carteira] = "Renegociacao" then 100007 else if [Carteira] = "Transportadora" then 100008 else if [Carteira] = "Verba" then 100009 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"xCODCART", type number}})
				in
				  #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

