table TB_AUXtempo
	lineageTag: 12a8b3a6-b32c-438d-a0f0-937b4732c8ca

	column ID
		dataType: int64
		formatString: 0
		lineageTag: b4547133-5f75-4817-9e06-89e9c7e66b41
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column DESC
		dataType: string
		lineageTag: 2e54b8b1-bcf4-4459-8f02-70e91f1b3172
		summarizeBy: none
		sourceColumn: DESC
		sortByColumn: ID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 1e60e70c-dc19-4942-a527-12f532617952
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	partition TB_AUXtempo = m
		mode: import
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jdAxC8IwEIbhv3JkUqxw1zRJMwoK4uLmUjuEmqFLB4v/34uSxSTEKfDycJBvGAQhohGNuL8Q5QQGjrNbYQN72HK9+WWaH24VY/OlmqMBB6QqUHFk5EBiRXYcGTnQNSk56iBtTbYcbZDU1yjFz/s/cM/xfL2c4hO7zSy4+5w4QDjin5ESJgsWIKULFmSbLliQmQULssssWKAqu+AvHt8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, DESC = _t, Tipo = _t]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Origem, {{"ID", Int64.Type}, {"DESC", type text}, {"Tipo", type text}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

