table TB_Apoio
	lineageTag: 53a96aa3-334b-435a-9fd8-446c402e9f68

	column potador
		dataType: string
		lineageTag: 864ca48f-d0d9-4e91-afb2-bed4747f1810
		summarizeBy: none
		sourceColumn: potador

		annotation SummarizationSetBy = Automatic

	column 'apoio para a view'
		dataType: string
		lineageTag: 69defa47-d5ea-4c61-a392-ac12bc457833
		summarizeBy: none
		sourceColumn: apoio para a view

		annotation SummarizationSetBy = Automatic

	column descrição
		dataType: string
		lineageTag: b9c94965-0202-44a2-91fd-b4532e2e58ac
		summarizeBy: none
		sourceColumn: descrição

		annotation SummarizationSetBy = Automatic

	column Carteira
		dataType: string
		lineageTag: 0740718b-2c40-4c7d-b6d9-870db27ddbcf
		summarizeBy: none
		sourceColumn: Carteira

		annotation SummarizationSetBy = Automatic

	column xCODCART
		dataType: double
		lineageTag: 0966cbef-4b84-4eec-abdd-b61d54b1b9fb
		summarizeBy: none
		sourceColumn: xCODCART
		sortByColumn: Carteira

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition TB_Apoio = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pdUxboMwFAbgqyDmpGOljjY2JBEQZBykCjE4xIMrCihALtShB8nF6qZSG2+Nfzbkp0/2z/OjrkOaFeEqFLrVR3PRZgrWwXge3vSsTsousGXsTKtmNQVRZ3Q/6+8Kpqd26G8lzaoONyTHEcFi2CASNxJScXwjucSRfcEFHitn+GmofNwozfvY6ekGMPKK72IrCY5QwUoYKdKIYoEkNAcjjYhAhVxuMIHkiUeX3wsv9sEEwT1Gzz1QxgTv7ggTbGsfMIEKn8vh5EDi6nGhMn27dH+3i3gMYNewWTyjhv0i8FnKbewxfV0j3UuPaeMaheAZamSH1KPHXYNXPn8j1xA82v0Yy6jP6vp5/RiC3XIyrVGdrbYLT7/v/y9smi8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [potador = _t, #"apoio para a view" = _t, descrição = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Origem,{{"potador", type text}, {"apoio para a view", type text}, {"descrição", type text}}),
				    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Tipo Alterado", "Carteira", each Text.AfterDelimiter([descrição], "- "), type text),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Texto Inserido Após o Delimitador", "xCODCART", each if [Carteira] = "Descontada" then 100001 else if [Carteira] = "Simples" then 100002 else if [Carteira] = "Vinculada" then 100003 else if [Carteira] = "Rec. Judicial" then 100004 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"xCODCART", type number}})
				in
				  #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

