table TB_Apoio
	lineageTag: 53a96aa3-334b-435a-9fd8-446c402e9f68

	column potador
		dataType: string
		lineageTag: 864ca48f-d0d9-4e91-afb2-bed4747f1810
		summarizeBy: none
		sourceColumn: potador

		annotation SummarizationSetBy = Automatic

	column 'apoio para a view'
		dataType: string
		lineageTag: 69defa47-d5ea-4c61-a392-ac12bc457833
		summarizeBy: none
		sourceColumn: apoio para a view

		annotation SummarizationSetBy = Automatic

	column descrição
		dataType: string
		lineageTag: b9c94965-0202-44a2-91fd-b4532e2e58ac
		summarizeBy: none
		sourceColumn: descrição

		annotation SummarizationSetBy = Automatic

	column Carteira
		dataType: string
		lineageTag: 0740718b-2c40-4c7d-b6d9-870db27ddbcf
		summarizeBy: none
		sourceColumn: Carteira

		annotation SummarizationSetBy = Automatic

	column xCODCART
		dataType: double
		lineageTag: 0966cbef-4b84-4eec-abdd-b61d54b1b9fb
		summarizeBy: sum
		sourceColumn: xCODCART
		sortByColumn: Carteira

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition TB_Apoio = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tZfNctowEMdfRcM5pIFkSDnKskxEwWZs42mTycEYlXHHsajBeYGe+hidHjp9Dl6sK/EVJxMLrCknQP/9abW7klYPDy1rPGldtHye8Fn6zNMVaqNlIb7xdTyPYcAul1maxOt4hUiW8nzNpcLmq0TkSvJ48dC6w645xLcdYwYOzRkDHFFzR9zQHOJNqG8eVmqbr8YKz2cE6dMy4ysFsPEXcy9YiM0hlm8HxpDJiFhmARlYboOQDjIxizOXrxWDYN8wLcQN784nEDEr4jzZF/qgQaG/dKIPHzOCTxucPi8BgYPNC5yYEaC6p2YEy2+yPypxwE50PiFK86TMjhsMNziDqwyIRc+UARkxXkvAnAYHcJUx8sIGB06VMfHp2JQxno4a1HiVQaMmF1KV4VMy3DLKJS/izZ/Nb4GG5TxN0jgDNQxcHn6fLpTocDj1/xMa27KY8PxZLOI1/C3eXa3UJDuNqkMaeVLMn0VWJvH7hkfFNkyu8jDnCwFe1BlWRCoOPpbGIZzSq6UoIDmieD89r2QSAGmW91vEi1lNWtWoKs9AVpZT5nOBArEL7iRexE+gFdUiUdsqvAEBI+MAKcsaqUMmZ6Eh2odgb9M65wendabkrakjihyqHSJTb0x8eQuSgs/T9VmGNpOnpcPwB4eyeunI2fyU2s3fIo01i7nudbvXIBlP0ADyyzP0aaExubm67d+CZJqnX0XxpAtX96bfkRNsfn0v0xxKgyMK35Z7Pcvn5WoNnqYaEFw6PkYRc2X4j2fFRev1ySHbYaxSdGjGpOhtlzjtXPU7t+0rDY9cMiSbfT1T3u6neKh0Ng3ISUQvwiMY21/AUvX6OgeUhxzmsrFmZnjFocAjjNpgpJ19j66ZXV59WO5y/aoJq+FgQrpaf0CEdv2PxnFZz9BgUNfTamV65TNMnwx4NaKA2FqdqlRtzMZepAsYddrOqC760vfte1i/xt3jWy+MPD/8rHFNdgmo0/vY67avT4JCezMNtEo1NRri+3vN/LLTYarJqAe6mx9em9nUDdu71vtk/a5NrtfLTscaTfVbCd5gIa5b1OM/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [potador = _t, #"apoio para a view" = _t, descrição = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Origem,{{"potador", type text}, {"apoio para a view", type text}, {"descrição", type text}}),
				    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Tipo Alterado", "Carteira", each Text.AfterDelimiter([descrição], "- "), type text),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Texto Inserido Após o Delimitador", "xCODCART", each if [Carteira] = "Descontada" then 100001 else if [Carteira] = "Simples" then 100002 else if [Carteira] = "Vinculada" then 100003 else if [Carteira] = "Rec. Judicial" then 100004 else if [Carteira] = "Advocaticio" then 100005 else if [Carteira] = "Devolucao" then 100006 else if [Carteira] = "Renegociacao" then 100007 else if [Carteira] = "Transportadora" then 100008 else if [Carteira] = "Verba" then 100009 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"xCODCART", type number}})
				in
				  #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

