table TB_Apoio
	lineageTag: 53a96aa3-334b-435a-9fd8-446c402e9f68

	column potador
		dataType: string
		lineageTag: 864ca48f-d0d9-4e91-afb2-bed4747f1810
		summarizeBy: none
		sourceColumn: potador

		annotation SummarizationSetBy = Automatic

	column 'apoio para a view'
		dataType: string
		lineageTag: 69defa47-d5ea-4c61-a392-ac12bc457833
		summarizeBy: none
		sourceColumn: apoio para a view

		annotation SummarizationSetBy = Automatic

	column descrição
		dataType: string
		lineageTag: b9c94965-0202-44a2-91fd-b4532e2e58ac
		summarizeBy: none
		sourceColumn: descrição

		annotation SummarizationSetBy = Automatic

	column Carteira
		dataType: string
		lineageTag: 0740718b-2c40-4c7d-b6d9-870db27ddbcf
		summarizeBy: none
		sourceColumn: Carteira

		annotation SummarizationSetBy = Automatic

	column xCODCART
		dataType: double
		lineageTag: 0966cbef-4b84-4eec-abdd-b61d54b1b9fb
		summarizeBy: sum
		sourceColumn: xCODCART
		sortByColumn: Carteira

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition TB_Apoio = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("tVfNctowEH4VDeeQBpIh5ShkmYr6h7GNp00mB2NUxh3HogbnBXrqY3R66PQ5eLGuxE8CmVhgtZwAffvtr3ZX9/etgTtuXbQCnvJp9sSzJWqjRSm+8lUyS+DAqhZ5liarZIlInvFixSXC4stUFArycHHf+oA9c5LAso05cGTOMcQxNTfEi8xJ/DENzMNKrfM54qxIq3zvzCA6nyLMHhc5XyoCC39uYMSRIyzC5iSDwAqNScYOGZgFZDjwGoR0mItpknt8pTgIDgzTQrzow/kMREzLpEh3dT5sUOcvjejDx4whoA2az0uC0MbmBU7MGKC6J2YMg6DJ/TiIA7Zj014BVjRowYccEIueKQdkxNiXkNkN+u8hh+NH/6DhBNQ1NcSdOA2K/MgQGjeZSIeGBJSMNhzVgpfJ+vf6l0CjapalWZIDGg4u979PB0rqaDQJ/hM1tmQ54dmTmCcr+Fu86a3EpFuMqkQa+xLMn0Repcnbgs+ITZg8ZWHB5wKsqBM8AKk4BFgKR9CnlwtRQnJE+XZ6jmCSANIsJ1zMy2lNWtWpqs9QlpZdFTOBQrEN7jiZJ4+AFYdFoi5WdAMARtwQKckaqE3GZ1FDtPfB3qR1xvdG60TJa1FblAVUO0SmXpgEcg6Sks+y1VmCFpP90mb4nU1ZPdSx1z8kdv2nzBKNM9e9bvcaIO4YDSG/PEcf5xqRm6vb/i1AJkX2RZSPunB1b/odqWD981uVFVAaHFH4ttjhWTGrliuwNNMQwdgJMIqZJ8P/3CsuWsedQ+7DWKVo35Qk6PWeOOlc9Tu37SsNH7lkSG77ek4530+xUOEsGpKTGP0YO3C2G8ESdTzQgcpHNvOYq9EMzzgU+oRRC4S02nfUNdrl8MPyluu9JkyrEBPSPQWEtnuQxnxZ1bBoUM/XYmWS5WtMnxJ4PKKQWFqcqldt5Fw/1oWN2m3bqcuBtH3zLNb7uH2D64GxH0SfNKbJZQF1eu973fb1SaSw5kxCLVKpRiN8d6fRLxceplaNekJv/d1vM4t6UXu7gp+M367L9Xi57wycif5CwVsswhqnwgjrPXKdSO8GvOm7dcoe/gI=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [potador = _t, #"apoio para a view" = _t, descrição = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Origem,{{"potador", type text}, {"apoio para a view", type text}, {"descrição", type text}}),
				    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Tipo Alterado", "Carteira", each Text.AfterDelimiter([descrição], "- "), type text),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Texto Inserido Após o Delimitador", "xCODCART", each if [Carteira] = "Descontada" then 100001 else if [Carteira] = "Simples" then 100002 else if [Carteira] = "Vinculada" then 100003 else if [Carteira] = "Rec. Judicial" then 100004 else if [Carteira] = "Advocaticio" then 100005 else if [Carteira] = "Devolucao" then 100006 else if [Carteira] = "Renegociacao" then 100007 else if [Carteira] = "Transportadora" then 100008 else if [Carteira] = "Verba" then 100009 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"xCODCART", type number}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

