table TB_CLI
	lineageTag: 5f91deec-ad69-46b5-9dd2-57ff32ddb158

	column xREDE = RELATED(TB_Rede[codgre]) &" - "& RELATED(TB_Rede[nomgre])
		lineageTag: 084b93f3-51e1-4472-b80b-e182883402ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column xLocalizacao =
			
			TB_CLI[NOMPAI] & "-" & TB_CLI[SIGUFS]
		lineageTag: 1fe2846a-c296-4625-8c03-a6b543a6a549
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column xOperacao
		dataType: string
		lineageTag: d9c287bd-1ae4-4b23-a13e-4a448d56b3e9
		summarizeBy: none
		sourceColumn: xOperacao

		annotation SummarizationSetBy = Automatic

	column xCliente = TB_CLI[codcli] &" - "& TB_CLI[nomcli]
		lineageTag: 6ed20906-a49d-40c6-ae7a-36e73bc1ab1a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CODCLI
		dataType: double
		lineageTag: 9c53c06e-910c-4e32-bcae-014db8334fb6
		summarizeBy: sum
		sourceColumn: CODCLI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NOMCLI
		dataType: string
		lineageTag: f4e94ca9-f14b-44af-be44-9616403f2b0a
		summarizeBy: none
		sourceColumn: NOMCLI

		annotation SummarizationSetBy = Automatic

	column CGCCPF
		dataType: double
		lineageTag: ad7a9fe7-b22f-4037-86bb-7df56654a390
		summarizeBy: sum
		sourceColumn: CGCCPF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column APECLI
		dataType: string
		lineageTag: d5627e1f-b262-4d91-8011-6bb3b1a3b055
		summarizeBy: none
		sourceColumn: APECLI

		annotation SummarizationSetBy = Automatic

	column USU_PERDUP
		dataType: string
		lineageTag: a4416785-ca3f-4949-9535-b70eef4f46e6
		summarizeBy: none
		sourceColumn: USU_PERDUP

		annotation SummarizationSetBy = Automatic

	column MARCLI
		dataType: string
		lineageTag: 2486173d-ea4f-4ff6-a821-e6694283874f
		summarizeBy: none
		sourceColumn: MARCLI

		annotation SummarizationSetBy = Automatic

	column CODGRE
		dataType: string
		lineageTag: bdb53341-690a-48fb-9b77-7ad71de1e553
		summarizeBy: none
		sourceColumn: CODGRE

		annotation SummarizationSetBy = Automatic

	column CEPCLI
		dataType: double
		lineageTag: 7924e6ae-bd79-4398-bdfd-f1cc74bd1b55
		summarizeBy: sum
		sourceColumn: CEPCLI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ENDCLI
		dataType: string
		lineageTag: bc351a39-5157-4cb7-ae2a-1b1b162fbcf4
		summarizeBy: none
		sourceColumn: ENDCLI

		annotation SummarizationSetBy = Automatic

	column CIDCLI
		dataType: string
		lineageTag: ff122c26-184b-4874-b09c-9022a6ee21e9
		summarizeBy: none
		sourceColumn: CIDCLI

		annotation SummarizationSetBy = Automatic

	column SIGUFS
		dataType: string
		lineageTag: 99b08a4b-ab21-465e-8044-13f77c6b335b
		summarizeBy: none
		sourceColumn: SIGUFS

		annotation SummarizationSetBy = Automatic

	column FONCLI
		dataType: string
		lineageTag: a33177e5-7cbd-46ad-9090-53e5bc2707ed
		summarizeBy: none
		sourceColumn: FONCLI

		annotation SummarizationSetBy = Automatic

	column DATCAD
		dataType: dateTime
		formatString: General Date
		lineageTag: 7cfbd7ac-7c0b-4f61-a34a-2e256cc022f7
		summarizeBy: none
		sourceColumn: DATCAD

		variation Variation
			isDefault
			relationship: b22f5e7a-3837-4e2c-bc69-065446ec64b3
			defaultHierarchy: LocalDateTable_883c164d-f052-4b3b-bd11-0400d4339e97.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column SITCLI
		dataType: string
		lineageTag: 39b1031d-f4c7-44a8-b49e-ac1e9e82fb0f
		summarizeBy: none
		sourceColumn: SITCLI

		annotation SummarizationSetBy = Automatic

	column CODREP
		dataType: double
		lineageTag: 03ca8643-630a-4215-96b7-1b82d41d7d03
		summarizeBy: sum
		sourceColumn: CODREP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NOMREP
		dataType: string
		lineageTag: 4d584de3-6226-42f0-8a7b-750e571004cd
		summarizeBy: none
		sourceColumn: NOMREP

		annotation SummarizationSetBy = Automatic

	column CODPAI
		dataType: string
		lineageTag: edb0b831-446f-48f9-b9dd-769098e0c689
		summarizeBy: none
		sourceColumn: CODPAI

		annotation SummarizationSetBy = Automatic

	column NOMPAI
		dataType: string
		lineageTag: 9fda6644-48d7-44cb-b097-65f51f518ffc
		summarizeBy: none
		sourceColumn: NOMPAI

		annotation SummarizationSetBy = Automatic

	column CODRAM
		dataType: string
		lineageTag: 59c32cec-79ef-4e4e-a122-0e8c9ab3968b
		summarizeBy: none
		sourceColumn: CODRAM

		annotation SummarizationSetBy = Automatic

	column USU_CODRAM
		dataType: string
		lineageTag: 0c575e81-15eb-4917-82eb-7dcb62357651
		summarizeBy: none
		sourceColumn: USU_CODRAM

		annotation SummarizationSetBy = Automatic

	column USU_DESRAM
		dataType: string
		lineageTag: 40508825-4644-4861-95e9-3b75ddbaf5ec
		summarizeBy: none
		sourceColumn: USU_DESRAM

		annotation SummarizationSetBy = Automatic

	column SITFINANCEIRO
		dataType: string
		lineageTag: 5bd818e5-2e93-4aa8-a9b0-904ccae9b1ca
		summarizeBy: none
		sourceColumn: SITFINANCEIRO

		annotation SummarizationSetBy = Automatic

	column SITINADIMPLENCIA
		dataType: string
		lineageTag: 5149f03e-de74-4c66-95e6-8745f42ad1f8
		summarizeBy: none
		sourceColumn: SITINADIMPLENCIA

		annotation SummarizationSetBy = Automatic

	column CODCPG
		dataType: string
		lineageTag: df0c2a99-c686-4fe7-b3d9-90462b15ffb5
		summarizeBy: none
		sourceColumn: CODCPG

		annotation SummarizationSetBy = Automatic

	column ABRCPG
		dataType: string
		lineageTag: 960a29a0-158d-4d7b-bf52-6922fc3fa4ba
		summarizeBy: none
		sourceColumn: ABRCPG

		annotation SummarizationSetBy = Automatic

	column VLRLIM
		dataType: double
		lineageTag: 86bcaf87-1a6c-4049-9cfe-626fb86a7da5
		summarizeBy: sum
		sourceColumn: VLRLIM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EXIAGE
		dataType: string
		lineageTag: 8b262132-5d26-40ba-ac8f-8d66bd4592dd
		summarizeBy: none
		sourceColumn: EXIAGE

		annotation SummarizationSetBy = Automatic

	column DEP_PADRAO
		dataType: string
		lineageTag: f7ed2354-b679-4aa9-a255-f1eee555586e
		summarizeBy: none
		sourceColumn: DEP_PADRAO

		annotation SummarizationSetBy = Automatic

	partition TB_CLI = m
		mode: import
		queryGroup: _Dim
		source = ```
				let
				  Origem = Oracle.Database("147.15.121.67:49182/I260220090255_p.subnetappxts2p.saaspremiumvcn1.oraclevcn.com", [HierarchicalNavigation = true]),
				  
				  #"Navegação 1" = Origem{[Schema = "I260220090255_ERPP"]}[Data],
				  #"Navegação 2" = Table.Buffer(#"Navegação 1"{[Name = "USU_V085CLI"]}[Data]),
				    #"Valor Substituído" = Table.ReplaceValue(
				        #"Navegação 2",
				        null,
				        "7",
				        Replacer.ReplaceValue,
				        {"USU_CODRAM"}
				    ),
				    #"Valor Substituído1" = Table.ReplaceValue(
				        #"Valor Substituído",
				        " ",
				        "NÃO CLASSIFICADO",
				        Replacer.ReplaceValue,
				        {"USU_DESRAM"}
				    ),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído1",{{"CODGRE", type text}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"CODGRE"}, TB_OPRede, {"codgre"}, "TB_OPRede", JoinKind.LeftOuter),
				    #"TB_OPRede Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "TB_OPRede", {"CODOP"}, {"CODOP"}),
				    #"Consultas Mescladas1" = Table.NestedJoin(#"TB_OPRede Expandido", {"SIGUFS"}, TB_OPUf, {"UF"}, "TB_OPUf", JoinKind.LeftOuter),
				    #"TB_OPUf Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas1", "TB_OPUf", {"CODOP"}, {"CODOP.1"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"TB_OPUf Expandido", "xOperacao", each if [CODOP] = null then [CODOP.1] else [CODOP]),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Condicional Adicionada",{"CODOP", "CODOP.1"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas",{{"xOperacao", type text}})
				in
				    #"Tipo Alterado1"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

