table TB_CTA
	lineageTag: 4411d2e5-f8f3-42c6-b390-99624670fdde

	column xAgrupamento =
			
			VAR Conta = TB_CTA[ctafin]
			RETURN
			IF(
			    CONTAINS(
			        fxFluxoCaixa(2),
			        [CtaFin], Conta
			    ),
			    SWITCH(
			        TRUE(),
			        Conta IN {1060,2040,3730,850,1800,3350,3921,2840}, "01. Consumo",
			        Conta IN {1080,530,610,640,630,660,620,520,580,710,650,560,570,590,3050,2540}, "02. Matéria Prima",
			        Conta IN {540,670,3850,700,3910,680,500}, "03. Embalagem",
			        Conta IN {1100,1890}, "04. Manutenção",
			        "05. A Classificar"
			    ),
			    BLANK()
			)
		lineageTag: 7d7c0d81-c4ed-4517-8fd8-16b8b3cb948f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column xAGP =
			
			VAR vCustoProducao = { 1060,3730,2040,850,1800,1080,1100,1890,530,540,610,640,630,650,660,670,620,520,580,3850,710,560,700,570,3910,680,590,500,3050,3350,2840,3921,2540,720,3750,2080 }
			VAR vCustoDespesasComerciais = { 1330,3640,1550,3610,3040,2490,4051,3860,1250,1650,1160,1640,490,1720,1750,3140,1390,1340,2520,4001,1290,1320,1990 }
			VAR vDespesasADM = { 3981,840,3150,1070,2810,3880,920,2030,2030,2020,1980,1960,190,280,2000,3780,1110,2530,2950,2820,2640,2970,3830,2480,310,1130,290,200,240,2260,3530,930,1200,2510,2510,1730,1930,1910,870,860,1000,2330,2010,1700,1030,3560,940,1920,960,1140,170,3660,230,350,880,980,2360,160,990,140,970,1850,2651,1090,1190,210,270,180,1440,260,300,2150,2140 }
			VAR vIMPOSTOS = { 770 }
			VAR vDespesasFinanceira = { 70, 420, 3690 }
			
			RETURN
			SWITCH(
			    TRUE(),
			    TB_CTA[ctafin] IN vCustoProducao , "01. Producao",
			    TB_CTA[ctafin] IN vCustoDespesasComerciais , "02. Despesas Comerciais",
			    TB_CTA[ctafin] IN vDespesasADM , "03. Despesas Administrativas",
			    TB_CTA[ctafin] IN vIMPOSTOS , "04. Impostos",
			    TB_CTA[ctafin] IN vDespesasFinanceira , "05. Despesas Financeiras",
			    "06. A Classificar" )
		lineageTag: b38abe3a-7be9-404c-9559-15165f41725f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CTAFIN
		dataType: double
		lineageTag: f3b16933-ca36-4ee5-a5f8-c45882550a8f
		summarizeBy: sum
		sourceColumn: CTAFIN

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DESCTA
		dataType: string
		lineageTag: b79090e0-2cee-4391-9b34-deba5873e2f1
		summarizeBy: none
		sourceColumn: DESCTA

		annotation SummarizationSetBy = Automatic

	column ABRCTA
		dataType: string
		lineageTag: 3b39a9a9-c7d9-4ed8-9512-290d6cf33502
		summarizeBy: none
		sourceColumn: ABRCTA

		annotation SummarizationSetBy = Automatic

	partition TB_CTA = m
		mode: import
		queryGroup: _Dim
		source = ```
				let
				    Origem = Oracle.Database("147.15.121.67:49182/I260220090255_p.subnetappxts2p.saaspremiumvcn1.oraclevcn.com", [HierarchicalNavigation = true]),
				
				  #"Navegação 1" = Origem{[Schema = "I260220090255_ERPP"]}[Data],
				  #"Navegação 2" = #"Navegação 1"{[Name = "E091PLF"]}[Data], 
				
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Navegação 2",{"CTAFIN", "DESCTA", "ABRCTA"})
				in
				    #"Outras Colunas Removidas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

