table TB_CLI
	lineageTag: 5f91deec-ad69-46b5-9dd2-57ff32ddb158

	column codcli
		dataType: string
		lineageTag: cdbf2faa-56fc-4661-95dd-0760ae647143
		summarizeBy: none
		sourceColumn: codcli

		annotation SummarizationSetBy = Automatic

	column nomcli
		dataType: string
		lineageTag: a217866c-4f9e-4b95-9ec3-e4a2b3a8532a
		summarizeBy: none
		sourceColumn: nomcli

		annotation SummarizationSetBy = Automatic

	column cgccpf
		dataType: int64
		formatString: 0
		lineageTag: fa303fe8-1e59-44c8-b774-bff370ea26e1
		summarizeBy: sum
		sourceColumn: cgccpf

		annotation SummarizationSetBy = Automatic

	column apecli
		dataType: string
		lineageTag: db82f0c3-e569-4808-804c-dec4a6d054be
		summarizeBy: none
		sourceColumn: apecli

		annotation SummarizationSetBy = Automatic

	column usu_perdup
		dataType: string
		lineageTag: 99147a99-048a-41f9-9792-d6eb052f2317
		summarizeBy: none
		sourceColumn: usu_perdup

		annotation SummarizationSetBy = Automatic

	column marcli
		dataType: string
		lineageTag: d11e8092-97aa-4057-8992-8f3fd048888d
		summarizeBy: none
		sourceColumn: marcli

		annotation SummarizationSetBy = Automatic

	column codgre
		dataType: string
		lineageTag: 9a33043e-ecdc-4cd0-bb9d-b00e2441fe83
		summarizeBy: none
		sourceColumn: codgre

		annotation SummarizationSetBy = Automatic

	column cepcli
		dataType: int64
		formatString: 0
		lineageTag: a1e6fcac-c888-4903-9612-69127c17b5b3
		summarizeBy: sum
		sourceColumn: cepcli

		annotation SummarizationSetBy = Automatic

	column endcli
		dataType: string
		lineageTag: a866d302-7b5a-48c9-b269-117d38524ad5
		summarizeBy: none
		sourceColumn: endcli

		annotation SummarizationSetBy = Automatic

	column cidcli
		dataType: string
		lineageTag: 8a26cf4f-c139-4da2-9768-338418aa1a35
		summarizeBy: none
		sourceColumn: cidcli

		annotation SummarizationSetBy = Automatic

	column sigufs
		dataType: string
		lineageTag: 6b0da039-54b2-4d9e-ad2a-8ddc74246b1d
		summarizeBy: none
		sourceColumn: sigufs

		annotation SummarizationSetBy = Automatic

	column foncli
		dataType: string
		lineageTag: 58dae212-1154-44f0-b38f-8eebbd64daa9
		summarizeBy: none
		sourceColumn: foncli

		annotation SummarizationSetBy = Automatic

	column datcad
		dataType: dateTime
		formatString: General Date
		lineageTag: 12df55a6-ad83-4731-9716-ec31993e3fd9
		summarizeBy: none
		sourceColumn: datcad

		variation Variation
			isDefault
			relationship: a1e2672a-1c56-4674-b30b-d37836518f36
			defaultHierarchy: LocalDateTable_9b806f60-4aa9-4692-b2d1-3455339e17ac.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column sitcli
		dataType: string
		lineageTag: 4b2c7927-b0bc-4dd8-b97b-dfa9114a9bd6
		summarizeBy: none
		sourceColumn: sitcli

		annotation SummarizationSetBy = Automatic

	column codrep
		dataType: string
		lineageTag: d8689090-1266-47b0-9e6e-4109fe22e497
		summarizeBy: none
		sourceColumn: codrep

		annotation SummarizationSetBy = Automatic

	column nomrep
		dataType: string
		lineageTag: caaf74a9-9729-40fb-8127-be3a865ad379
		summarizeBy: none
		sourceColumn: nomrep

		annotation SummarizationSetBy = Automatic

	column codpai
		dataType: string
		lineageTag: fc8a0fb6-2ab2-46c4-b87b-d9904d5c6e65
		summarizeBy: none
		sourceColumn: codpai

		annotation SummarizationSetBy = Automatic

	column nompai
		dataType: string
		lineageTag: d24a3e1e-1327-41b3-b7ce-677104d7eed7
		summarizeBy: none
		sourceColumn: nompai

		annotation SummarizationSetBy = Automatic

	column codram
		dataType: string
		lineageTag: e07bc511-865b-492c-be1b-26fbb72d81c1
		summarizeBy: none
		sourceColumn: codram

		annotation SummarizationSetBy = Automatic

	column usu_codram
		dataType: string
		lineageTag: 18fbd71f-6d7d-4523-a993-276acb9a3791
		summarizeBy: none
		sourceColumn: usu_codram

		annotation SummarizationSetBy = Automatic

	column usu_desram
		dataType: string
		lineageTag: a6826a43-9748-470c-aeff-1be9f64e2bac
		summarizeBy: none
		sourceColumn: usu_desram

		annotation SummarizationSetBy = Automatic

	column SitFinanceiro
		dataType: string
		lineageTag: baab214d-4c5e-4ce3-999a-3207d7e50694
		summarizeBy: none
		sourceColumn: SitFinanceiro

		annotation SummarizationSetBy = Automatic

	column SitInadimplencia
		dataType: string
		lineageTag: 73c92799-6c84-4bf6-b9df-c67ea7900a7e
		summarizeBy: none
		sourceColumn: SitInadimplencia

		annotation SummarizationSetBy = Automatic

	column codcpg
		dataType: string
		lineageTag: ffbda30c-6bb2-412b-bf7d-5f1d3e5f9300
		summarizeBy: none
		sourceColumn: codcpg

		annotation SummarizationSetBy = Automatic

	column abrcpg
		dataType: string
		lineageTag: a977a8b7-c4f6-452e-acdd-888fc5a2d0e6
		summarizeBy: none
		sourceColumn: abrcpg

		annotation SummarizationSetBy = Automatic

	column vlrlim
		dataType: double
		lineageTag: bf333855-7031-4a79-8628-5e024ef451b8
		summarizeBy: sum
		sourceColumn: vlrlim

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column exiage
		dataType: string
		lineageTag: bc88e19c-c1f3-4fa0-b259-e13b43d018bd
		summarizeBy: none
		sourceColumn: exiage

		annotation SummarizationSetBy = Automatic

	column Dep_Padrao
		dataType: string
		lineageTag: 0947ecf3-2c97-4bb3-8003-b6d0afcb18de
		summarizeBy: none
		sourceColumn: Dep_Padrao

		annotation SummarizationSetBy = Automatic

	column xREDE = RELATED(TB_Rede[codgre]) &" - "& RELATED(TB_Rede[nomgre])
		lineageTag: 084b93f3-51e1-4472-b80b-e182883402ed
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column xLocalizacao =
			
			TB_CLI[nompai] & "-" & TB_CLI[sigufs]
		lineageTag: 1fe2846a-c296-4625-8c03-a6b543a6a549
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition TB_CLI = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem = Sql.Database("159.112.182.77", "I260220090255_ERPP"),
				  #"Navegação 1" = Origem{[Schema = "sapiens_producao", Item = "usu_view085cli"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Navegação 1",{{"codcli", type text}, {"codrep", type text}, {"codgre", type text}})
				in
				  #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

