table TB_FRJ
	lineageTag: f91fd509-d40c-4b14-bdfd-59918a7d7723

	column xTipo
		dataType: string
		lineageTag: 15859bc7-b34b-4c5a-9b7e-74094cdfc24a
		summarizeBy: none
		sourceColumn: xTipo

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"TB_FRJ","TableItemName":"xTipo (grupos)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'xTipo (grupos)' =
			SWITCH(
				TRUE,
				ISBLANK('TB_FRJ'[xTipo]),
				"(Em branco)",
				'TB_FRJ'[xTipo] IN {"Data Especifica"},
				"Data Especifica",
				'TB_FRJ'[xTipo] IN {"Devolucao"},
				"Devolucao",
				'TB_FRJ'[xTipo] IN {"Não entregue"},
				"Entrega Pendente",
				'TB_FRJ'[xTipo] IN {"Inadimplencia"},
				"Inadimplencia",
				'TB_FRJ'[xTipo] IN {"Negociando"},
				"Negociando",
				'TB_FRJ'[xTipo] IN {"Prorogacao Atraso na entrega",
					"Prorrog. Erro Boleto / Subst.",
					"Prorrog. Fat. Antec. +7D",
					"Prorrog. Fluxo Pgto Cliente"},
				"Prorrogacao",
				'TB_FRJ'[xTipo] IN {"Sem Classificacao"},
				"Sem Classificacao",
				'TB_FRJ'[xTipo] IN {"Verba"},
				"Verba",
				"Demais Classif."
			)
		lineageTag: 324daf7f-08fc-48bf-a093-0077bfa47270
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "TB_FRJ"
				          }
				        },
				        "Property": "xTipo"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"t","Entity":"TB_FRJ"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"GroupItems":[{"DisplayName":"(Em branco)","BlankDefaultPlaceholder":true},{"DisplayName":"Data Especifica","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Data Especifica'"}}]]}}},{"DisplayName":"Devolucao","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Devolucao'"}}]]}}},{"DisplayName":"Entrega Pendente","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Não entregue'"}}]]}}},{"DisplayName":"Inadimplencia","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Inadimplencia'"}}]]}}},{"DisplayName":"Negociando","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Negociando'"}}]]}}},{"DisplayName":"Prorrogacao","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Prorogacao Atraso na entrega'"}}],[{"Literal":{"Value":"'Prorrog. Erro Boleto / Subst.'"}}],[{"Literal":{"Value":"'Prorrog. Fat. Antec. +7D'"}}],[{"Literal":{"Value":"'Prorrog. Fluxo Pgto Cliente'"}}]]}}},{"DisplayName":"Sem Classificacao","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Sem Classificacao'"}}]]}}},{"DisplayName":"Verba","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"t"}},"Property":"xTipo"}}],"Values":[[{"Literal":{"Value":"'Verba'"}}]]}}},{"DisplayName":"Demais Classif."}]}

		annotation SummarizationSetBy = Automatic

	column CODFRJ
		dataType: string
		lineageTag: 2143ec13-d030-4a4b-86c8-9c103290ee03
		summarizeBy: none
		sourceColumn: CODFRJ

		annotation SummarizationSetBy = Automatic

	column DESFRJ
		dataType: string
		lineageTag: 912eb5e8-b9e8-4eaf-a741-0e5f0a9db60f
		summarizeBy: none
		sourceColumn: DESFRJ

		annotation SummarizationSetBy = Automatic

	partition TB_FRJ = m
		mode: import
		queryGroup: _Dim
		source = ```
				let
				  Origem = Oracle.Database("147.15.121.67:49182/I260220090255_p.subnetappxts2p.saaspremiumvcn1.oraclevcn.com", [HierarchicalNavigation = true]),
				  
				  #"Navegação 1" = Origem{[Schema = "I260220090255_ERPP"]}[Data],
				  #"Navegação 2" = Table.Buffer(#"Navegação 1"{[Name = "E037FRJ"]}[Data]),
				
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Navegação 2",{"CODFRJ", "DESFRJ"}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Outras Colunas Removidas", "xTipo", each 
				        if [CODFRJ] = "910" then "Global" else 
				        if [CODFRJ] = "600" then "Verba" else
				        if [CODFRJ] = "980" then "Inadimplencia" else 
				        if [CODFRJ] = "JUR" then "Juridico" else
				        if [CODFRJ] = "500" then "Negociando" else
					      if [CODFRJ] = "700" then "Devolucao" else
				        if [CODFRJ] = "940" then "Não entregue" else
				        if [CODFRJ] = "SIN" then "Sinistro" else
				        if [CODFRJ] = "900" then "Resolução Interna" else
				        if [CODFRJ] = "400" then "Erro Digitacao" else
				        if [CODFRJ] = "300" then "Data Especifica" else
				        if [CODFRJ] = "800" then "Exportacao" else
				        if [CODFRJ] = "FUN" then "Funcionario" else
				        if [CODFRJ] = "100" then "Prorogacao Atraso na entrega" else
				        if [CODFRJ] = "CER" then "Cervejaria" 
				        else [DESFRJ]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"xTipo", type text}}),
				    #"LinhaBlanck" = Table.InsertRows(#"Tipo Alterado", 0, {[CODFRJ = "00", DESFRJ = "Nao Classificado", xTipo = "Sem Classificacao"]} )
				in
				    #"LinhaBlanck"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

