table TB_Operacao
	lineageTag: 61b14280-6e51-4def-a10c-7028c2dcd9a6

	column CODOP
		dataType: string
		lineageTag: 07c64f81-dfaa-4095-91e3-284ab2cde71a
		summarizeBy: none
		sourceColumn: CODOP

		annotation SummarizationSetBy = Automatic

	column OP
		dataType: string
		lineageTag: e1c7eca1-9012-41a0-a072-16736d6b6d27
		summarizeBy: none
		sourceColumn: OP

		annotation SummarizationSetBy = Automatic

	partition TB_Operacao = m
		mode: import
		queryGroup: _DimPlan
		source =
				let
				  Origem = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1esuc7Rg7pQNpYThQFH_4EQYL1KOAQrYqz8CK-wnHWIU/edit?gid=1377226161#gid=1377226161"),
				  #"Navegação 1" = Origem{[name = "Base", ItemKind = "Table"]}[Data],
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Navegação 1",{"Column4", "Column5"}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Outras Colunas Removidas", [PromoteAllScalars=true]),
				    #"Linhas Filtradas" = Table.SelectRows(#"Cabeçalhos Promovidos", each ([CODOP] <> "")),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas Filtradas",{{"CODOP", type text}, {"OP", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

