table TB_PGT
	lineageTag: 9e5c01df-4d39-4a8c-8bde-7274a7f26aa1

	column CODFPG
		dataType: string
		lineageTag: 12658007-4f51-4434-9f3e-20c6e7900ac5
		summarizeBy: none
		sourceColumn: CODFPG

		annotation SummarizationSetBy = Automatic

	column DESFPG
		dataType: string
		lineageTag: 3cb62d33-c1c4-4245-bbe6-eb44e5e21bb0
		summarizeBy: none
		sourceColumn: DESFPG

		annotation SummarizationSetBy = Automatic

	column ABRFPG
		dataType: string
		lineageTag: 11c83deb-76ab-40cf-a674-1e57e97ff435
		summarizeBy: none
		sourceColumn: ABRFPG

		annotation SummarizationSetBy = Automatic

	partition TB_PGT = m
		mode: import
		queryGroup: _Dim
		source = ```
				let
				  Origem = Oracle.Database("147.15.121.67:49182/I260220090255_p.subnetappxts2p.saaspremiumvcn1.oraclevcn.com", [HierarchicalNavigation = true]),
				  
				  #"Navegação 1" = Origem{[Schema = "I260220090255_ERPP"]}[Data],
				  #"Navegação 2" = #"Navegação 1"{[Name = "E066FPG"]}[Data],
				
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Navegação 2",{"CODFPG", "DESFPG", "ABRFPG"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Outras Colunas Removidas",{{"CODFPG", type text}})
				in
				  #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

