table TB_RTerceiros
	lineageTag: 74b93616-09f4-4cc7-a515-2997d00b3fdf

	column Contas
		dataType: string
		lineageTag: b13393e3-2e3b-4e1f-8243-0d06bb217b4a
		summarizeBy: none
		sourceColumn: Contas

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: dateTime
		formatString: Long Date
		lineageTag: 842d8c12-9fed-41ab-b75a-97aabea5bf2b
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: double
		lineageTag: ddec5004-4f20-4c4f-b2fc-2567aee1d207
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column xIDTerceiros
		dataType: string
		lineageTag: ccd3612b-205b-4efd-8fde-de4b34893025
		summarizeBy: none
		sourceColumn: xIDTerceiros

		annotation SummarizationSetBy = Automatic

	column codBanco
		dataType: string
		lineageTag: 92f0f3ac-1a8c-45fb-92ac-5f73929db706
		summarizeBy: none
		sourceColumn: codBanco

		annotation SummarizationSetBy = Automatic

	column Banco
		dataType: string
		lineageTag: 26676c69-6359-455f-812f-088d6d567bbb
		summarizeBy: none
		sourceColumn: Banco

		annotation SummarizationSetBy = Automatic

	partition TB_RTerceiros = m
		mode: import
		queryGroup: _Fatos
		source =
				let
				  Origem = Excel.Workbook(File.Contents("\\dados\Financeiro\CR\CR\RECURSOS DE TERCEIROS.xlsx"), null, true),
				  #"Navegação 1" = Origem{[Item = "Planilha1", Kind = "Sheet"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(#"Navegação 1",{"Column1"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Column2] <> null)),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Linhas Filtradas",1),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Contas", type text}, {"01/01/2025", type number}, {"02/01/2025", type number}, {"03/01/2025", type number}, {"04/01/2025", type number}, {"05/01/2025", type number}, {"06/01/2025", type number}, {"07/01/2025", type number}, {"08/01/2025", type number}, {"09/01/2025", type number}, {"10/01/2025", type number}, {"11/01/2025", type number}, {"12/01/2025", type number}, {"13/01/2025", type number}, {"14/01/2025", type number}, {"15/01/2025", type number}, {"16/01/2025", type number}, {"17/01/2025", type number}, {"18/01/2025", type number}, {"19/01/2025", type number}, {"20/01/2025", type number}, {"21/01/2025", type number}, {"22/01/2025", type number}, {"23/01/2025", type number}, {"24/01/2025", type number}, {"25/01/2025", type number}, {"26/01/2025", type number}, {"27/01/2025", type number}, {"28/01/2025", type number}, {"29/01/2025", type number}, {"30/01/2025", type number}, {"31/01/2025", type number}, {"01/02/2025", type number}, {"02/02/2025", type number}, {"03/02/2025", type number}, {"04/02/2025", type number}, {"05/02/2025", type number}, {"06/02/2025", type number}, {"07/02/2025", type number}, {"08/02/2025", type number}, {"09/02/2025", type number}, {"10/02/2025", type number}, {"11/02/2025", type number}, {"12/02/2025", type number}, {"13/02/2025", type number}, {"14/02/2025", type number}, {"15/02/2025", type number}, {"16/02/2025", type number}, {"17/02/2025", type number}, {"18/02/2025", type number}, {"19/02/2025", type number}, {"20/02/2025", type number}, {"21/02/2025", type number}, {"22/02/2025", type number}, {"23/02/2025", type number}, {"24/02/2025", type number}, {"25/02/2025", type number}, {"26/02/2025", type number}, {"27/02/2025", type number}, {"28/02/2025", type number}, {"01/03/2025", type number}, {"02/03/2025", type number}, {"03/03/2025", type number}, {"04/03/2025", type number}, {"05/03/2025", type number}, {"06/03/2025", type number}, {"07/03/2025", type number}, {"08/03/2025", type number}, {"09/03/2025", type number}, {"10/03/2025", type number}, {"11/03/2025", type number}, {"12/03/2025", type number}, {"13/03/2025", type number}, {"14/03/2025", type number}, {"15/03/2025", type number}, {"16/03/2025", type number}, {"17/03/2025", type number}, {"18/03/2025", type number}, {"19/03/2025", type number}, {"20/03/2025", type number}, {"21/03/2025", type number}, {"22/03/2025", type number}, {"23/03/2025", type number}, {"24/03/2025", type number}, {"25/03/2025", type number}, {"26/03/2025", type number}, {"27/03/2025", type number}, {"28/03/2025", type number}, {"29/03/2025", type number}, {"30/03/2025", type number}, {"31/03/2025", type number}, {"01/04/2025", type number}, {"02/04/2025", type number}, {"03/04/2025", type number}, {"04/04/2025", type number}, {"05/04/2025", type number}, {"06/04/2025", type number}, {"07/04/2025", type number}, {"08/04/2025", type number}, {"09/04/2025", type number}, {"10/04/2025", type number}, {"11/04/2025", type number}, {"12/04/2025", type number}, {"13/04/2025", type number}, {"14/04/2025", type number}, {"15/04/2025", type number}, {"16/04/2025", type number}, {"17/04/2025", type number}, {"18/04/2025", type number}, {"19/04/2025", type number}, {"20/04/2025", type number}, {"21/04/2025", type number}, {"22/04/2025", type number}, {"23/04/2025", type number}, {"24/04/2025", type number}, {"25/04/2025", type number}, {"26/04/2025", type number}, {"27/04/2025", type number}, {"28/04/2025", type number}, {"29/04/2025", type number}, {"30/04/2025", type number}, {"01/05/2025", type number}, {"02/05/2025", type number}, {"03/05/2025", type number}, {"04/05/2025", type number}, {"05/05/2025", type number}, {"06/05/2025", type number}, {"07/05/2025", type number}, {"08/05/2025", type number}, {"09/05/2025", type number}, {"10/05/2025", type number}, {"11/05/2025", type number}, {"12/05/2025", type number}, {"13/05/2025", type number}, {"14/05/2025", type number}, {"15/05/2025", type number}, {"16/05/2025", type number}, {"17/05/2025", type number}, {"18/05/2025", type number}, {"19/05/2025", type number}, {"20/05/2025", type number}, {"21/05/2025", type number}, {"22/05/2025", type number}, {"23/05/2025", type number}, {"24/05/2025", type number}, {"25/05/2025", type number}, {"26/05/2025", type number}, {"27/05/2025", type number}, {"28/05/2025", type number}, {"29/05/2025", type number}, {"30/05/2025", type number}, {"31/05/2025", type number}, {"01/06/2025", type number}, {"02/06/2025", type number}, {"03/06/2025", type number}, {"04/06/2025", type number}, {"05/06/2025", type number}, {"06/06/2025", type number}, {"07/06/2025", type number}, {"08/06/2025", type number}, {"09/06/2025", type number}, {"10/06/2025", type number}, {"11/06/2025", type number}, {"12/06/2025", type number}, {"13/06/2025", type number}, {"14/06/2025", type number}, {"15/06/2025", type number}, {"16/06/2025", type number}, {"17/06/2025", type number}, {"18/06/2025", type number}, {"19/06/2025", type number}, {"20/06/2025", type number}, {"21/06/2025", type number}, {"22/06/2025", type number}, {"23/06/2025", type number}, {"24/06/2025", type number}, {"25/06/2025", type number}, {"26/06/2025", type number}, {"27/06/2025", type number}, {"28/06/2025", type number}, {"29/06/2025", type number}, {"30/06/2025", type number}, {"01/07/2025", type number}, {"02/07/2025", type number}, {"03/07/2025", type number}, {"04/07/2025", type number}, {"05/07/2025", type number}, {"06/07/2025", type number}, {"07/07/2025", type number}, {"08/07/2025", type number}, {"09/07/2025", type number}, {"10/07/2025", type number}, {"11/07/2025", type number}, {"12/07/2025", type number}, {"13/07/2025", type number}, {"14/07/2025", type number}, {"15/07/2025", type number}, {"16/07/2025", type number}, {"17/07/2025", type number}, {"18/07/2025", type number}, {"19/07/2025", type number}, {"20/07/2025", type number}, {"21/07/2025", type number}, {"22/07/2025", type number}, {"23/07/2025", type number}, {"24/07/2025", type number}, {"25/07/2025", type number}, {"26/07/2025", type number}, {"27/07/2025", type number}, {"28/07/2025", type number}, {"29/07/2025", type number}, {"30/07/2025", type number}, {"31/07/2025", type number}, {"01/08/2025", type number}, {"02/08/2025", type number}, {"03/08/2025", type number}, {"04/08/2025", type number}, {"05/08/2025", type number}, {"06/08/2025", type number}, {"07/08/2025", type number}, {"08/08/2025", type number}, {"09/08/2025", type number}, {"10/08/2025", type number}, {"11/08/2025", type number}, {"12/08/2025", type number}, {"13/08/2025", type number}, {"14/08/2025", type number}, {"15/08/2025", type number}, {"16/08/2025", type number}, {"17/08/2025", type number}, {"18/08/2025", type number}, {"19/08/2025", type number}, {"20/08/2025", type number}, {"21/08/2025", type number}, {"22/08/2025", type number}, {"23/08/2025", type number}, {"24/08/2025", type number}, {"25/08/2025", type number}, {"26/08/2025", type number}, {"27/08/2025", type number}, {"28/08/2025", type number}, {"29/08/2025", type number}, {"30/08/2025", type number}, {"31/08/2025", type number}, {"01/09/2025", type number}, {"02/09/2025", type number}, {"03/09/2025", type number}, {"04/09/2025", type number}, {"05/09/2025", type number}, {"06/09/2025", type number}, {"07/09/2025", type number}, {"08/09/2025", type number}, {"09/09/2025", type number}, {"10/09/2025", type number}, {"11/09/2025", type number}, {"12/09/2025", type number}, {"13/09/2025", type number}, {"14/09/2025", type number}, {"15/09/2025", type number}, {"16/09/2025", type number}, {"17/09/2025", type number}, {"18/09/2025", type number}, {"19/09/2025", type number}, {"20/09/2025", type number}, {"21/09/2025", type number}, {"22/09/2025", type number}, {"23/09/2025", type number}, {"24/09/2025", type number}, {"25/09/2025", type number}, {"26/09/2025", type number}, {"27/09/2025", type number}, {"28/09/2025", type number}, {"29/09/2025", type number}, {"30/09/2025", type number}, {"01/10/2025", type number}, {"02/10/2025", type number}, {"03/10/2025", type number}, {"04/10/2025", type number}, {"05/10/2025", type number}, {"06/10/2025", type number}, {"07/10/2025", type number}, {"08/10/2025", type number}, {"09/10/2025", type number}, {"10/10/2025", type number}, {"11/10/2025", type number}, {"12/10/2025", type number}, {"13/10/2025", type number}, {"14/10/2025", type number}, {"15/10/2025", type number}, {"16/10/2025", type number}, {"17/10/2025", type number}, {"18/10/2025", type number}, {"19/10/2025", type number}, {"20/10/2025", type number}, {"21/10/2025", type number}, {"22/10/2025", type number}, {"23/10/2025", type number}, {"24/10/2025", type number}, {"25/10/2025", type number}, {"26/10/2025", type number}, {"27/10/2025", type number}, {"28/10/2025", type number}, {"29/10/2025", type number}, {"30/10/2025", type number}, {"31/10/2025", type number}, {"01/11/2025", type number}, {"02/11/2025", type number}, {"03/11/2025", type number}, {"04/11/2025", type any}, {"05/11/2025", type any}, {"06/11/2025", type any}, {"07/11/2025", type any}, {"08/11/2025", type any}, {"09/11/2025", type any}, {"10/11/2025", type any}, {"11/11/2025", type any}, {"12/11/2025", type any}, {"13/11/2025", type any}, {"14/11/2025", type any}, {"15/11/2025", type any}, {"16/11/2025", type any}, {"17/11/2025", type any}, {"18/11/2025", type any}, {"19/11/2025", type any}, {"20/11/2025", type any}, {"21/11/2025", type any}, {"22/11/2025", type any}, {"23/11/2025", type any}, {"24/11/2025", type any}, {"25/11/2025", type any}, {"26/11/2025", type any}, {"27/11/2025", type any}, {"28/11/2025", type any}, {"29/11/2025", type any}, {"30/11/2025", type number}, {"01/12/2025", type number}, {"02/12/2025", type number}, {"03/12/2025", type number}, {"04/12/2025", type number}, {"05/12/2025", type number}, {"06/12/2025", type number}, {"07/12/2025", type number}, {"08/12/2025", type number}, {"09/12/2025", type number}, {"10/12/2025", type number}, {"11/12/2025", type number}, {"12/12/2025", type number}, {"13/12/2025", type number}, {"14/12/2025", type number}, {"15/12/2025", type number}, {"16/12/2025", type number}, {"17/12/2025", type number}, {"18/12/2025", type number}, {"19/12/2025", type number}, {"20/12/2025", type number}, {"21/12/2025", type number}, {"22/12/2025", type number}, {"23/12/2025", type number}, {"24/12/2025", type number}, {"25/12/2025", type number}, {"26/12/2025", type number}, {"27/12/2025", type number}, {"28/12/2025", type number}, {"29/12/2025", type number}, {"30/12/2025", type number}, {"31/12/2025", type number}, {"01/01/2026", type number}, {"02/01/2026", type number}, {"03/01/2026", type number}, {"04/01/2026", type number}, {"05/01/2026", type number}, {"06/01/2026", type number}, {"07/01/2026", type number}, {"08/01/2026", type number}, {"09/01/2026", type number}, {"10/01/2026", type number}, {"11/01/2026", type number}, {"12/01/2026", type number}, {"13/01/2026", type number}, {"14/01/2026", type number}, {"15/01/2026", type number}, {"16/01/2026", type number}, {"17/01/2026", type number}, {"18/01/2026", type number}, {"19/01/2026", type number}, {"20/01/2026", type number}, {"21/01/2026", type number}, {"22/01/2026", type number}, {"23/01/2026", type number}, {"24/01/2026", type number}, {"25/01/2026", type number}, {"26/01/2026", type number}, {"27/01/2026", type number}, {"28/01/2026", type number}, {"29/01/2026", type number}, {"30/01/2026", type number}, {"31/01/2026", type number}, {"01/02/2026", type number}, {"02/02/2026", type number}, {"03/02/2026", type number}, {"04/02/2026", type number}, {"05/02/2026", type number}, {"06/02/2026", type number}, {"07/02/2026", type number}, {"08/02/2026", type number}, {"09/02/2026", type number}, {"10/02/2026", type number}, {"11/02/2026", type number}, {"12/02/2026", type number}, {"13/02/2026", type number}, {"14/02/2026", type number}, {"15/02/2026", type number}, {"16/02/2026", type number}, {"17/02/2026", type number}, {"18/02/2026", type number}, {"19/02/2026", type number}, {"20/02/2026", type number}, {"21/02/2026", type number}, {"22/02/2026", type number}, {"23/02/2026", type number}, {"24/02/2026", type number}, {"25/02/2026", type number}, {"26/02/2026", type number}, {"27/02/2026", type number}, {"28/02/2026", type number}, {"01/03/2026", type number}, {"02/03/2026", type number}, {"03/03/2026", type number}, {"04/03/2026", type number}, {"05/03/2026", type number}, {"06/03/2026", type number}, {"07/03/2026", type number}, {"08/03/2026", type number}, {"09/03/2026", type number}, {"10/03/2026", type number}, {"11/03/2026", type number}, {"12/03/2026", type number}, {"13/03/2026", type number}, {"14/03/2026", type number}, {"15/03/2026", type number}, {"16/03/2026", type number}, {"17/03/2026", type number}, {"18/03/2026", type number}, {"19/03/2026", type number}, {"20/03/2026", type number}, {"21/03/2026", type number}, {"22/03/2026", type number}, {"23/03/2026", type number}, {"24/03/2026", type number}, {"25/03/2026", type number}, {"26/03/2026", type number}, {"27/03/2026", type number}, {"28/03/2026", type number}, {"29/03/2026", type number}, {"30/03/2026", type number}, {"31/03/2026", type number}, {"01/04/2026", type number}, {"02/04/2026", type number}, {"03/04/2026", type number}, {"04/04/2026", type number}, {"05/04/2026", type number}, {"06/04/2026", type number}, {"07/04/2026", type number}, {"08/04/2026", type number}, {"09/04/2026", type number}, {"10/04/2026", type number}, {"11/04/2026", type number}, {"12/04/2026", type number}, {"13/04/2026", type number}, {"14/04/2026", type number}, {"15/04/2026", type number}, {"16/04/2026", type number}, {"17/04/2026", type number}, {"18/04/2026", type number}, {"19/04/2026", type number}, {"20/04/2026", type number}, {"21/04/2026", type number}, {"22/04/2026", type number}, {"23/04/2026", type number}, {"24/04/2026", type number}, {"25/04/2026", type number}, {"26/04/2026", type number}, {"27/04/2026", type number}, {"28/04/2026", type number}, {"29/04/2026", type number}, {"30/04/2026", type number}, {"01/05/2026", type number}, {"02/05/2026", type number}, {"03/05/2026", type number}, {"04/05/2026", type number}, {"05/05/2026", type number}, {"06/05/2026", type number}, {"07/05/2026", type number}, {"08/05/2026", type number}, {"09/05/2026", type number}, {"10/05/2026", type number}, {"11/05/2026", type number}, {"12/05/2026", type number}, {"13/05/2026", type number}, {"14/05/2026", type number}, {"15/05/2026", type number}, {"16/05/2026", type number}, {"17/05/2026", type number}, {"18/05/2026", type number}, {"19/05/2026", type number}, {"20/05/2026", type number}, {"21/05/2026", type number}, {"22/05/2026", type number}, {"23/05/2026", type number}, {"24/05/2026", type number}, {"25/05/2026", type number}, {"26/05/2026", type number}, {"27/05/2026", type number}, {"28/05/2026", type number}, {"29/05/2026", type number}, {"30/05/2026", type number}, {"31/05/2026", type number}, {"01/06/2026", type number}, {"02/06/2026", type number}, {"03/06/2026", type number}, {"04/06/2026", type number}, {"05/06/2026", type number}, {"06/06/2026", type number}, {"07/06/2026", type number}, {"08/06/2026", type number}, {"09/06/2026", type number}, {"10/06/2026", type number}, {"11/06/2026", type number}, {"12/06/2026", type number}, {"13/06/2026", type number}, {"14/06/2026", type number}, {"15/06/2026", type number}, {"16/06/2026", type number}, {"17/06/2026", type number}, {"18/06/2026", type number}, {"19/06/2026", type number}, {"20/06/2026", type number}, {"21/06/2026", type number}, {"22/06/2026", type number}, {"23/06/2026", type number}, {"24/06/2026", type number}, {"25/06/2026", type number}, {"26/06/2026", type number}, {"27/06/2026", type number}, {"28/06/2026", type number}, {"29/06/2026", type number}, {"30/06/2026", type number}, {"01/07/2026", type number}, {"02/07/2026", type any}, {"03/07/2026", type any}, {"04/07/2026", type any}, {"05/07/2026", type any}, {"06/07/2026", type any}, {"07/07/2026", type any}, {"08/07/2026", type any}, {"09/07/2026", type any}, {"10/07/2026", type any}, {"11/07/2026", type any}, {"12/07/2026", type any}, {"13/07/2026", type any}, {"14/07/2026", type any}, {"15/07/2026", type any}, {"16/07/2026", type any}, {"17/07/2026", type any}, {"18/07/2026", type any}, {"19/07/2026", type any}, {"20/07/2026", type any}, {"21/07/2026", type any}, {"22/07/2026", type any}, {"23/07/2026", type any}, {"24/07/2026", type any}, {"25/07/2026", type any}, {"26/07/2026", type any}, {"27/07/2026", type any}, {"28/07/2026", type any}, {"29/07/2026", type any}, {"30/07/2026", type any}, {"31/07/2026", type any}, {"01/08/2026", type any}, {"02/08/2026", type any}, {"03/08/2026", type any}, {"04/08/2026", type any}, {"05/08/2026", type any}, {"06/08/2026", type any}, {"07/08/2026", type any}, {"08/08/2026", type any}, {"09/08/2026", type any}, {"10/08/2026", type any}, {"11/08/2026", type any}, {"12/08/2026", type any}, {"13/08/2026", type any}, {"14/08/2026", type any}, {"15/08/2026", type any}, {"16/08/2026", type any}, {"17/08/2026", type any}, {"18/08/2026", type any}, {"19/08/2026", type any}, {"20/08/2026", type any}, {"21/08/2026", type any}, {"22/08/2026", type any}, {"23/08/2026", type any}, {"24/08/2026", type any}, {"25/08/2026", type any}, {"26/08/2026", type any}, {"27/08/2026", type any}, {"28/08/2026", type any}, {"29/08/2026", type any}, {"30/08/2026", type any}, {"31/08/2026", type any}, {"01/09/2026", type any}, {"02/09/2026", type any}, {"03/09/2026", type any}, {"04/09/2026", type any}, {"05/09/2026", type any}, {"06/09/2026", type any}, {"07/09/2026", type any}, {"08/09/2026", type any}, {"09/09/2026", type any}, {"10/09/2026", type any}, {"11/09/2026", type any}, {"12/09/2026", type any}, {"13/09/2026", type any}, {"14/09/2026", type any}, {"15/09/2026", type any}, {"16/09/2026", type any}, {"17/09/2026", type any}, {"18/09/2026", type any}, {"19/09/2026", type any}, {"20/09/2026", type any}, {"21/09/2026", type any}, {"22/09/2026", type any}, {"23/09/2026", type any}, {"24/09/2026", type any}, {"25/09/2026", type any}, {"26/09/2026", type any}, {"27/09/2026", type any}, {"28/09/2026", type any}, {"29/09/2026", type any}, {"30/09/2026", type any}, {"01/10/2026", type any}, {"02/10/2026", type any}, {"03/10/2026", type any}, {"04/10/2026", type any}, {"05/10/2026", type any}, {"06/10/2026", type any}, {"07/10/2026", type any}, {"08/10/2026", type any}, {"09/10/2026", type any}, {"10/10/2026", type any}, {"11/10/2026", type any}, {"12/10/2026", type any}, {"13/10/2026", type any}, {"14/10/2026", type any}, {"15/10/2026", type any}, {"16/10/2026", type any}, {"17/10/2026", type any}, {"18/10/2026", type any}, {"19/10/2026", type any}}),
				    #"Outras Colunas Não Dinâmicas" = Table.UnpivotOtherColumns(#"Tipo Alterado", {"Contas"}, "Atributo", "Valor"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Outras Colunas Não Dinâmicas",{{"Valor", type number}, {"Atributo", type date}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado1", each [Atributo] > #date(2026, 1, 1)),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Filtradas1", "xIDTerceiros", each if [Contas] = "BRADESCO" then "10001_01" else if [Contas] = "BRADESCO FINIM" then "10001_02" else if [Contas] = "BRADESCO GARANTIA" then "10001_03" else if [Contas] = "DAYC VINC" then "20001_02" else if [Contas] = "DAYCOVAL" then "20001_01" else if [Contas] = "ITAU" then "30001_01" else if [Contas] = "ITAU10917-0" then "30001_02" else if [Contas] = "SAFRA" then "40001_01" else if [Contas] = "SAFRA GARAN" then "40001_03" else if [Contas] = "SAFRA GARAN II" then "40001_03" else if [Contas] = "SAFRA GARAN I" then "40001_03" else if [Contas] = "SAFRA VINC" then "40001_02" else if [Contas] = "SAFRA - VINC" then "40001_02" else if [Contas] = "DAYCOVAL GAR I" then "20001_03" else if [Contas] = "DAYCOVAL GARAN" then "20001_03" else null),
				    #"Valor Substituído" = Table.ReplaceValue(#"Coluna Condicional Adicionada",0,null,Replacer.ReplaceValue,{"Valor"}),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Valor Substituído", each ([xIDTerceiros] <> null)),
				    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Linhas Filtradas2", "codBanco", each Text.BeforeDelimiter([xIDTerceiros], "_"), type text),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Texto Inserido Antes do Delimitador", "Banco", each if [codBanco] = "10001" then "Bradesco" else if [codBanco] = "20001" then "Daycoval" else if [codBanco] = "30001" then "Itau" else if [codBanco] = "40001" then "Safra" else null),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada1",{{"xIDTerceiros", type text}, {"Banco", type text}})
				in
				    #"Tipo Alterado2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

