table TB_REP
	lineageTag: 86af5e2e-ba01-4167-80a1-3391d231bfc5

	column CODREP
		dataType: string
		lineageTag: dc29c7cc-415f-4f8e-9d9f-33e5b63b4ac5
		summarizeBy: none
		sourceColumn: CODREP

		annotation SummarizationSetBy = Automatic

	column NOMREP
		dataType: string
		lineageTag: c5c40bb7-3765-473e-9bb1-a8b636da82c2
		summarizeBy: none
		sourceColumn: NOMREP

		annotation SummarizationSetBy = Automatic

	column APEREP
		dataType: string
		lineageTag: 35358cfe-5881-4a36-8f28-87deb0ff3892
		summarizeBy: none
		sourceColumn: APEREP

		annotation SummarizationSetBy = Automatic

	column TIPREP
		dataType: string
		lineageTag: 4ec10ae5-87ea-4e81-aad2-b3aa676df40e
		summarizeBy: none
		sourceColumn: TIPREP

		annotation SummarizationSetBy = Automatic

	column CIDREP
		dataType: string
		lineageTag: 0ce4337a-e6af-45e7-a8e1-ea69f42a0bca
		summarizeBy: none
		sourceColumn: CIDREP

		annotation SummarizationSetBy = Automatic

	column SIGUFS
		dataType: string
		lineageTag: 636d0bb7-07b2-4895-b0e4-09524218844d
		summarizeBy: none
		sourceColumn: SIGUFS

		annotation SummarizationSetBy = Automatic

	column FONREP
		dataType: string
		lineageTag: 131d7a88-c0ca-416d-aa40-6e72d920f7b1
		summarizeBy: none
		sourceColumn: FONREP

		annotation SummarizationSetBy = Automatic

	column SITREP
		dataType: string
		lineageTag: b5003518-3710-4aa1-91ad-bfb7c42b3200
		summarizeBy: none
		sourceColumn: SITREP

		annotation SummarizationSetBy = Automatic

	column REPSUP
		dataType: double
		lineageTag: facba63a-9545-42b0-89db-5aa9ae007ff4
		summarizeBy: sum
		sourceColumn: REPSUP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NOMSUP
		dataType: string
		lineageTag: 2e8eea7c-3fd7-4e4e-b19a-78ef41204dfa
		summarizeBy: none
		sourceColumn: NOMSUP

		annotation SummarizationSetBy = Automatic

	column REP_CONCAT
		dataType: double
		lineageTag: bc7adc4b-7d17-48b6-9e18-0aac5c0958bd
		summarizeBy: sum
		sourceColumn: REP_CONCAT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition TB_REP = m
		mode: import
		queryGroup: _Dim
		source = ```
				let
				  Origem = Oracle.Database("147.15.121.67:49182/I260220090255_p.subnetappxts2p.saaspremiumvcn1.oraclevcn.com", [HierarchicalNavigation = true]),
				  
				  #"Navegação 1" = Origem{[Schema = "I260220090255_ERPP"]}[Data],
				  #"Navegação 2" = #"Navegação 1"{[Name = "USU_V090REP"]}[Data],
				
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Navegação 2",{{"CODREP", type text}})
				in
				  #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

