table TB_TNS
	lineageTag: 8f2b86db-5d4c-42e0-9ae2-a48c6825c526

	column CODTNS
		dataType: string
		lineageTag: 3ff7c4d4-33fe-44a5-8db6-594261b180eb
		summarizeBy: none
		sourceColumn: CODTNS

		annotation SummarizationSetBy = Automatic

	column DESTNS
		dataType: string
		lineageTag: bce355e4-6919-4e27-8e3e-4d13945e4705
		summarizeBy: none
		sourceColumn: DESTNS

		annotation SummarizationSetBy = Automatic

	partition TB_TNS = m
		mode: import
		queryGroup: _Dim
		source =
				let
				  Origem =  Oracle.Database("(DESCRIPTION = (ENABLE=broken) (ADDRESS = (PROTOCOL = TCP)(HOST = 147.15.121.67 )(PORT = 49182))(CONNECT_DATA =(SERVICE_NAME = i260220090255_p.subnetappxts2p.saaspremiumvcn1.oraclevcn.com )))", [HierarchicalNavigation = true]),
				
				  #"Navegação 1" = Origem{[Schema = "I260220090255_ERPP"]}[Data],
				  #"Navegação 2" = #"Navegação 1"{[Name = "E001TNS"]}[Data],
				
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Navegação 2",{"CODTNS", "DESTNS"})
				in
				    #"Outras Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

