table xSenha
	lineageTag: 0efd0780-2589-42a0-9bec-78b257d3f4ec

	measure xAcessos = ```
			
			SWITCH(
			    TRUE(),
			    HASONEFILTER( xSenha[DESC] ) && xAcesso[Valor xAcesso] = MAX( xSenha[Senha] ), "Calendario", 
			    "Senha Incorreta"
			)
			```
		lineageTag: 774f6e4a-b811-41e0-8f24-77fc22b91f6a

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 412b94cc-46a5-4a38-bf87-ae6a4eadb9d4
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column DESC
		dataType: string
		lineageTag: cf65697f-e165-4661-8b83-3bb34d028730
		summarizeBy: none
		sourceColumn: DESC

		annotation SummarizationSetBy = Automatic

	column Senha
		dataType: int64
		formatString: 0
		lineageTag: 9efd939c-72e0-4f6f-a5a0-92fdf1da886d
		summarizeBy: sum
		sourceColumn: Senha

		annotation SummarizationSetBy = Automatic

	partition xSenha = m
		mode: import
		source =
				let
				  Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjQwMDBU0lFydPEFkoZGxuamhkqxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, DESC = _t, Senha = _t]),
				  #"Tipo de coluna alterado" = Table.TransformColumnTypes(Origem, {{"ID", Int64.Type}, {"DESC", type text}, {"Senha", Int64.Type}})
				in
				  #"Tipo de coluna alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

